shell.execute("rm", "main.lua")
local request = http.get("https://raw.githubusercontent.com/itzmarkoni/NovaCrafLLC/refs/heads/main/main.lua?refresh")
request.close()
shell.execute("wget", "https://raw.githubusercontent.com/itzmarkoni/NovaCrafLLC/refs/heads/main/main.lua?refresh")
sleep(2)
local main = require("main")
main.run()
